<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<title>Mineframeowrk | <?= $titulo ?></title>

	<!-- CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>

<style>
	.menu-ativo {
		background: #138baf;
		color: #fff;
	}

	header ul {
		list-style: none;
		display: flex;
	}
	header ul li {
		margin-right: 5px;
	}
	header ul li a{
		padding: 5px 10px;
		color: #333;
		text-decoration: none !important;
		border-radius: 500px;
		transition: 0.3s;
	}
	header ul li a:hover {
		background: #138baf;
		color: #fff;
	}
</style>

<body>
	<h1>Layout 1</h1>
	
	<header>
		<ul>
			<li><a href="/">Home</a></li>
			<li><a href="/sobre">Sobre</a></li>
		</ul>
	</header>
	

	<div id="root">
		<?= $this->content() ?>
	</div>


	<!-- jQuery, Porrer, Bootstrap  -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"
		integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
		integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
		integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
		crossorigin="anonymous"></script>

	<script src="./assets/js/script.js"></script>
</body>

</html>